server:
  port: 8080
app:
  dpop:
    required: ${DPOP_REQUIRED:true}
    debug-headers: ${DPOP_DEBUG_HEADERS:true}
spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OKTA_ISSUER:https://ntrsoiesys.oktapreview.com/oauth2/aus11aowjcqDJAtVk1d8}
          audiences: ${OKTA_AUDIENCE:https://ntrsoiesys.oktapreview.com}
management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    com.example.okta: ${APP_LOG_LEVEL:DEBUG}
